### ISSUE TITLE
Problem with require_once of relative path

### ISSUE THREAD

**Issue by geromey** [geelweb/Litmus#3]
Hello,

I use this library for quite a while and it works like a charm.

I recently moved to using composer for installing external libraries. The only problem I found is with the require_once calls with relative paths like this one : 

```php
require_once 'Litmus/RESTful/Server.php';
```

Composer manages to make the class mapping pretty well so it would work without it. The problem is that it is a relative path which only works if the current path is actually in the folder /vendor/geelweb/litmus/library

I managed to prevent the error by adding this folder to the with set_include_path() so the files are found.

It would be nice to change the relative path into absolute path.

For example, in the file library/Litmus/RESTful/Client.php : 

```php
require_once 'Litmus/RESTful/Server.php';
```

could become : 

```php
require_once __DIR__ . '/Server.php';
```

Thank you.

**Comment by adamaveray** [comment]
I'd like this too. Currently I'm working around this by doing the following before using the library:

~~~php
set_include_path(get_include_path().\PATH_SEPARATOR.__DIR__.'/vendor/geelweb/litmus/library/');
~~~

This adds the library's path to the global include path, letting those relative includes resolve. `__DIR__` based includes would of course be much better.
